### ISSUE TITLE
Invalid database query parameter value while running cron

### ISSUE THREAD

**Issue by ewallah** [moodlehq/moodle-tool_dataprivacy#1]
Execute adhoc task: tool_dataprivacy\task\initiate_data_request_task
... started 15:56:44. Current memory use 15.4MB.
Generating user metadata...
User metadata generation complete...
Notice: Object of class stdClass could not be converted to int in lib/classes/user.php on line 115
... used 10 dbqueries
... used 0.01447606086731 seconds
Adhoc task failed: tool_dataprivacy\task\initiate_data_request_task,Coding error detected, it must be fixed by a programmer: Invalid database query parameter value
Debug info:
Objects are are not allowed: stdClass
Backtrace:
* line 878 of /lib/dml/moodle_database.php: call to moodle_database->detect_objects()
* line 773 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->fix_sql_params()
* line 1571 of /lib/dml/moodle_database.php: call to pgsql_native_moodle_database->get_records_sql()
* line 1543 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
* line 1522 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
* line 123 of /lib/classes/user.php: call to moodle_database->get_record()
* line 412 of /admin/tool/dataprivacy/classes/api.php: call to core_user::get_user()
* line 88 of /admin/tool/dataprivacy/classes/task/initiate_data_request_task.php: call to tool_dataprivacy\api::notify_dpo()
* line 181 of /lib/cronlib.php: call to tool_dataprivacy\task\initiate_data_request_task->execute()
* line 74 of /lib/cronlib.php: call to cron_run_inner_adhoc_task()
* line 81 of /admin/cron.php: call to cron_run()

```
-- $messagetextdata['requestfor'] = fullname(core_user::get_user($requestingfor));
++ $messagetextdata['requestfor'] = fullname(core_user::get_user($requestingfor->id));
```

**Comment by junpataleta** [comment]
Thanks for reporting this. I fixed this issue in this commit: https://github.com/moodlehq/moodle-tool_dataprivacy/commit/0418027664e7b8ff9ada5a8a8f660f1a713be6a8

Closing this issue.
