### ISSUE TITLE
The applied fix for MDL-62460 won't work for the 3.4 and 3.3 versions of the tool

### ISSUE THREAD

**Issue by junpataleta** [moodlehq/moodle-tool_dataprivacy#53]
As [pointed out](https://tracker.moodle.org/browse/MDL-62460?focusedCommentId=626497&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-626497) by @paulholden, the bug reported in [MDL-62460](https://tracker.moodle.org/browse/MDL-62460) will still be present in the 3.4 and 3.3 versions of the tool as the 'valuehtmlcallback' attribute of the autocomplete form element was only added in 3.5.

We need to resolve this differently for 3.3 and 3.4.

**Comment by paulholden** [comment]
Hi @junpataleta, I've come up against this exact issue in a plugin I've developed - unless you can get [this commit](https://github.com/moodle/moodle/commit/a97c937033324c5af69a6ddb949170f6b9ee5313) backported to 3.3 & 3.4, then you'll need to follow these instructions in the [dev docs](https://docs.moodle.org/dev/lib/formslib.php_Form_Definition#autocomplete) to create your own form element based on the autocomplete one:

> When using the ajax option in an mform with validation etc - it is recommended to sub-class the php class "MoodleQuickForm_autocomplete" so that you can provide a list of name and values to populate the form element if the form is re-displayed due to a validation error. An example is admin/tool/lp/classes/form/framework_autocomplete.php.

This solution worked fine for us. The problem you'll then hit is what was resolved in the commit mentioned above - all HTML tags from your mustache template will be stripped out, so you'll lose user avatars, etc...

**Comment by paulholden** [comment]
Also, the following warning is displayed when the form loads (in 3.3) caused by MDL-62460 backport:

> Warning: htmlspecialchars() expects parameter 1 to be string, object given in /[dirroot]/lib/pear/HTML/Common.php on line 171

**Comment by junpataleta** [comment]
I created a patch here: https://github.com/moodlehq/moodle-tool_dataprivacy/compare/MOODLE_33_STABLE...junpataleta:MDL-62460-33

I'll have someone get a quick look and merge it if it's all good.

**Comment by junpataleta** [comment]
Fixes merged:
33: 1986699c33bd834e19561297947c7e166c0f3883
34: 64794a814a726aa9a287bfe10fbd804b75b1f76f

Closing this issue.
