### ISSUE TITLE
Install available updates error on validation of moodle

### ISSUE THREAD

**Issue by neeesn** [moodlehq/moodle-tool_dataprivacy#56]
In moodle 343+ build 20180524 ( https://www.screencast.com/t/BGp6puQp )we get this error : 

_Installing available updates
Downloading tool_dataprivacy ... OK
Validating tool_dataprivacy ... Error
  [Error] Required Moodle version [2017111304.00] 
Installation aborted due to validation failure_
( https://www.screencast.com/t/wP96hsma4 )

The plugin is in the list of plugins available for updating.
https://www.screencast.com/t/TqE9OPZDZPl

**Comment by stronk7** [comment]
Closing this issue. Archiving the repository.
